model:
  base_learning_rate: 4.5e-07
  target: ldm.models.autoencoder.VQModel
  params:
    # ckpt_path: "../modelf8.ckpt"
    ckpt_path: "./last.ckpt"
    embed_dim: 4
    n_embed: 16384
    monitor: val/rec_loss
    ddconfig:
      double_z: false
      z_channels: 4
      resolution: 128
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult:
      - 1
      - 2
      - 2
      - 4
      num_res_blocks: 2
      attn_resolutions:
      - 32
      dropout: 0.0
    lossconfig:
      target: src.taming-transformers.taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: false
        disc_in_channels: 3
        disc_num_layers: 2
        disc_start: 1
        disc_weight: 0.6
        codebook_weight: 1.0
data:
  target: src.taming-transformers.main.DataModuleFromConfig
  params:
    batch_size: 2
    num_workers: 1
    wrap: true
    train:
      target: src.taming-transformers.taming.data.custom.CustomTrain
      params:
        training_images_list_file: ../xx_train.txt
        size: 128
    validation:
      target: src.taming-transformers.taming.data.custom.CustomTest
      params:
        test_images_list_file: ../xx_test.txt
        size: 128
